server:
  port: 8883

spring:
  application:
    name: customer-service
  cloud:
    consul:
      discovery:
        register: true
        prefer-ip-address: true

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com:
      yourpackage: INFO

jwt:
  secret: aXW3Pz9FXa48kdfnFKE9393skfls93kdmSDF932jkLDs=
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
